# Rename this file to languages.toml to enable multilingual support
[zh-cn]
    enable = true
    languageName = "中文 (简体)"
    languagedirection = "ltr"
    title = "Jiahao 的博客"

[en]
    enable = false
    languageName = "English"
    languagedirection = "ltr"
    title = "Jiahao's blog"
    weight = 2
