# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Jiahao 的博客
subtitle:
description: Jiahao 的博客
keywords: 编程, VSCode, JavaScript, C++
author: Jiahao Li
favicon: https://gcore.jsdelivr.net/gh/xaoxuu/assets@master/favicon/favicon.ico
language:
  - zh-CN
timezone: "Europe/Helsinki"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://thejiahao.github.io/
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: google8715f1f25a72ba25.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  auto_detect: false
  line_number: true
  wrap: true

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: []
exclude: []
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: cjh_google_url_submitter
- type: cjh_bing_url_submitter
- type: cjh_baidu_url_submitter

# SEO
# 自动生成 sitemap
sitemap:
  path: sitemap.xml
  rel: true

# 文章永久链接
abbrlink:
  alg: crc32 # support crc16(default) and crc32
  rep: hex

# 防止外部链接降低权重
nofollow:
  enable: true
  field: site
  exclude: giscus.app

# 自动将链接提交到搜索引擎
hexo_submit_urls_to_search_engine:
  submit_condition: count # 链接被提交的条件，可选值：count | period 现仅支持 count
  count: 10 # 提交最新的 10 个链接
  period: 900 # 提交修改时间在 900 秒内的链接
  google: 0 # 是否向 Google 提交，可选值：1 | 0（0：否；1：是）
  bing: 1 # 是否向 Bing 提交，可选值：1 | 0（0：否；1：是）
  baidu: 0 # 是否向 Baidu 提交，可选值：1 | 0（0：否；1：是）
  txt_path: submit_urls.txt # 文本文档名，需要推送的链接会保存在此文本文档里
  bing_host: https://thejiahao.github.io/ # 在 Bing 站长平台中注册的域名
  bing_token: # 请注意这是您的秘钥，所以请不要把它直接发布在公众仓库里！
## 压缩静态文件
minify:
  preview: true ## 本地预览时是否压缩
  exclude: ["*.min.*"]
  js:
    enable: true
    sourceMap:
      enable: false ## 生成 sourceMap
      ## 将 sourceMappingURL 插入压缩后的 js 文件，如果为 false 则需要在浏览器开发者工具中手动添加 sourceMap
      sourceMappingURL: false ## //# sourceMappingURL=xxx.js.map
    ## 详细配置: https://github.com/terser/terser#minify-options
    options: {}
  css:
    enable: true
    ## 详细配置: https://github.com/clean-css/clean-css#compatibility-modes
    options: {}
  html:
    enable: true
    ## 详细配置: https://github.com/kangax/html-minifier#options-quick-reference
    options:
      minifyJS: true # Compressed JavaScript
      minifyCSS: true # CSS Compressed
      removeComments: true # Remove the comments
      collapseWhitespace: true # Delete any extra space
      removeAttributeQuotes: true # Delete attribute quotes
  image:
    enable: true
    svg:
      enable: true
      ## 详细配置: https://github.com/imagemin/imagemin-svgo#imageminsvgooptionsbuffer
      options: {}
    jpg:
      enable: true
      ## 详细配置: https://github.com/imagemin/imagemin-jpegtran#options
      options: {}
    png:
      enable: true
      ## 详细配置: https://github.com/imagemin/imagemin-pngquant#options
      options: {}
    gif:
      enable: true
      ## 详细配置: https://www.npmjs.com/package/imagemin-gifsicle#options
      options: {}
    webp:
      enable: false
      ## 详细配置: https://github.com/imagemin/imagemin-webp#options
      options: {}
  font:
    enable: false
    ## 详细配置: https://github.com/Lete114/fontmin-spider#api
    options: {}

# RSS
feed:
  enable: true
  type: atom
  path: atom.xml
  icon: https://avatars.githubusercontent.com/u/42709836

# Markdown 渲染
markdown:
  preset: default
  render:
    html: true
    xhtmlOut: false
    langPrefix: "language-"
    breaks: false
    linkify: true
    typographer: true
    quotes: "“”‘’"
  images:
    lazyload: false
    prepend_root: true
    post_asset: true
  inline: false # https://markdown-it.github.io/markdown-it/#MarkdownIt.renderInline
