seo:
  use_tags_as_keywords: true # front-matter 缺少关键词时使用文章标签
  use_excerpt_as_description: true # front-matter 缺少描述时使用文章摘要

# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 暗黑模式
      icon: fas fa-moon
      toggle: darkmode
  search: 搜索... # Search bar placeholder

# 侧边栏
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://avatars.githubusercontent.com/u/42709836
      shape: circle # circle, rectangle
      url: /about/
      title: Jiahao Li
      subtitle:
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true

    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5

    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/

    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: "#999"
      end_color: "#555"

# 文章布局
article:
  # 文章列表页面的文章卡片布局方案
  preview:
    scheme: landscape # landscape
    # pin icon for post
    pin_icon: https://gcore.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4cc.svg
    # auto generate title if not exist
    auto_title: true # false, true
    # auto generate excerpt if not exist
    auto_excerpt: true # false, true
    # show split line or not
    line_style: solid # hidden, solid, dashed, dotted
    # show readmore button
    readmore: auto # auto, always
  # 文章详情页面的文章卡片本体布局方案
  body:
    # 文章顶部信息
    # 从 meta_library 中取
    top_meta: [author, category, date, updated]
    # ----------------
    # 文章页脚组件
    footer_widget:
      # 参考资料、相关资料等 (for layout: post/docs)
      references:
        title: 参考资料
        icon: fas fa-quote-left
        # 在 front-matter 中:
        #   references:
        #     - title: 某篇文章
        #       url: https://
        # 即可显示此组件。
      # 版权声明组件 (for layout: post/docs)

    # 文章底部信息
    # 从 meta_library 中取
    bottom_meta: [tags]

    # meta library
    meta_library:
      # 默认文章作者（可在 front-matter 中覆盖）
      author:
        avatar: https://avatars.githubusercontent.com/u/42709836
        name: Jiahao
        url: /
      # 文章创建日期
      date:
        icon: fas fa-calendar-alt
        title: "发布于："
        format: "ll" # 日期格式 http://momentjs.com/docs/
      # 文章更新日期
      updated:
        icon: fas fa-edit
        title: "更新于："
        format: "ll" # 日期格式 http://momentjs.com/docs/
      # 文章分类
      category:
        icon: fas fa-folder-open
      # 文章标签
      tags:
        icon: fas fa-hashtag
      # 分享

cover:
  height_scheme: half # full, half
  scheme: focus # search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: false
    others: false
  background:

site_footer:
  layout: [social, license]
  social:
    - icon: fas fa-rss
      url: atom.xml
    - icon: fab fa-github
      url: https://github.com/TheJiahao

plugins:
  darkmode:
    enable: true
