seo:
  use_tags_as_keywords: true # front-matter 缺少关键词时使用文章标签
  use_excerpt_as_description: true # front-matter 缺少描述时使用文章摘要

# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: 博客
      icon: fa-solid fa-rss
      url: /
    - name: 分类
      icon: fa-solid fa-folder-open
      url: categories/
    - name: 标签
      icon: fa-solid fa-tags
      url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 暗黑模式
      icon: fas fa-moon
      toggle: darkmode
  search: 搜索... # Search bar placeholder

# 侧边栏
sidebar:
  # 主页、分类、归档等独立页面
  for_page: [blogger, category, tagcloud]
  # layout: docs/post 这类文章页面
  for_post: [toc]
  # 侧边栏组件库
  widget_library:
    # blogger info widget
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: /images/avatar.jpg
      shape: circle # circle, rectangle
      url: /about/
      title: Jiahao Li
      subtitle:
      jinrishici: false # Poetry Today. You can set a string, and it will be displayed when loading fails.
      social: true

    # toc widget (valid only in articles)
    toc:
      class: toc
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-list
        title: 本文目录
      list_number: false
      min_depth: 2
      max_depth: 5

    # category widget
    category:
      class: category
      display: [desktop] # [desktop, mobile]
      header:
        icon: fas fa-folder-open
        title: 文章分类
        url: /categories/

    # tagcloud widget
    tagcloud:
      class: tagcloud
      display: [desktop, mobile] # [desktop, mobile]
      header:
        icon: fas fa-tags
        title: 热门标签
        url: /tags/
      min_font: 14
      max_font: 24
      color: true
      start_color: "#999"
      end_color: "#555"

cover:
  height_scheme: half # full, half
  scheme: focus # search (搜索), dock (坞), featured (精选), focus (焦点)
  display:
    home: true
    archive: false
    others: false

plugins:
  darkmode:
    enable: true
