name: Set up
description: Set up Bun
inputs:
    args:
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - uses: oven-sh/setup-bun@v1

        - name: Install dependencies
          run: bun install --frozen-lockfile ${{ inputs.args }}
          shell: bash
