description = "个人博客，内容可能涵盖工具配置、技术、数学等。不定时更新。"

[footer]
    customText = ""

[sidebar]
    subtitle = "一个普通的计算机系学生"

[article.license]
    default = "内容遵循 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh-hans)"

[comments.giscus]
    lang = "zh-CN"
