[footer]
    customText = ""

[sidebar]
    subtitle = "A CS student"

[article.license]
    default = "Licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en)"

[comments.giscus]
    lang = "en"
