[footer]
    customText = ""

[sidebar]
    subtitle = "A CS student"

[article.license]
    default = 'Licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">CC BY-NC-SA 4.0</a>'

[comments.giscus]
    lang = "en"
