# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["posts"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.svg"
taxonomiesExcludedFromSitemap = ["tags"]
pagesEcludedFromIndex = ["term", "taxonomy"]

[author]
    name = "Jiahao Li"

[footer]
    since = 2020

[dateFormat]
    published = "2006-01-02"
    lastUpdated = "2006-01-02"

[sidebar]
    emoji = "🤔"

    [sidebar.avatar]
        enabled = true
        local = true
        src = "avatar.svg"

[article]
    math = false
    headingAnchor = true

    [article.license]
        enabled = true

## Widgets
[[widgets.homepage]]
    type = "search"

[[widgets.homepage]]
    type = "archives"

    [widgets.homepage.params]
        limit = 5

[[widgets.homepage]]
    type = "categories"

    [widgets.homepage.params]
        limit = 10

[[widgets.homepage]]
    type = "tag-cloud"

    [widgets.homepage.params]
        limit = 10

[[widgets.page]]
    type = "toc"

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[defaultImage.opengraph]
    enabled = true
    local = false
    src = "https://raw.githubusercontent.com/microsoft/fluentui-emoji/14053d26005b9afe3ce0e020862ed5ab2335f989/assets/Thinking%20face/Flat/thinking_face_flat.svg"

[colorScheme]
    toggle = false
    default = "auto"

[imageProcessing.cover]
    enabled = true

[imageProcessing.content]
    enabled = true

## Comments
[comments]
    enabled = true
    provider = "giscus"

    [comments.disqusjs]
        shortname = ""
        apiUrl = ""
        apiKey = ""
        admin = ""
        adminLabel = ""

    [comments.utterances]
        repo = ""
        issueTerm = "pathname"
        label = ""

    [comments.remark42]
        host = ""
        site = ""
        locale = ""

    [comments.vssue]
        platform = ""
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
        autoCreateIssue = false

    [comments.waline]
        serverURL = ""
        lang = ""
        visitor = ""
        avatar = ""
        emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
        requiredMeta = ["name", "email", "url"]
        placeholder = ""

        [comments.waline.locale]
            admin = "Admin"

[comments.twikoo]
    envId = ""
    region = ""
    path = ""
    lang = ""

[comments.cactus]
    defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
    serverName = "cactus.chat"
    siteName = ""

[comments.giscus]
    repo = "TheJiahao/TheJiahao.github.io"
    repoID = "MDEwOlJlcG9zaXRvcnkyOTc3MDMxMjY="
    category = "General"
    categoryID = "DIC_kwDOEb6W1s4Cb_e4"
    mapping = "pathname"
    lightTheme = "light_tritanopia"
    darkTheme = "dark_tritanopia"
    reactionsEnabled = 1
    emitMetadata = 0

[comments.gitalk]
    owner = ""
    admin = ""
    repo = ""
    clientID = ""
    clientSecret = ""

[comments.cusdis]
    host = ""
    id = ""
