languageCode = "zh-cn"
languageName = "中文 (简体)"
languagedirection = "ltr"
title = "Jiahao 的博客"
weight = -1
# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = true
