name: CD
on:
  workflow_run:
    workflows: CI
    branches: main
    types: completed
  workflow_dispatch:

env:
  BING_TOKEN: ${{ secrets.BING_TOKEN }}

jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ github.event.workflow_dispatch }} != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./setup-action
        with:
          pnpm_args: -P

      - name: Generate static assets
        run: pnpm run build

      - name: Deploy to public repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: TheJiahao/TheJiahao.github.io
          publish_branch: main # default: gh-pages
          publish_dir: ./public
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: Deploy

  Submit_url_to_search_engines:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./setup-action
        with:
          pnpm_args: -P

      - name: Generate static assets
        run: pnpm run build

      - name: Save Google API key to JSON file        
        uses: SpicyPizza/create-envfile@v2.0.2
        with:
          envkey_SECRET_KEY: ${{ secrets.GOOGLE_INDEXING_API_JSON }}
          file_name: google_api_key.json
  
      - name: Submit URLs to search engines
        run: pnpm hexo deploy