name: CD
on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: ./setup-action

      - name: Deploy to GitHub Pages
        run: pnpm run deploy
