name: CD
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      INDEXNOW_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    env:
      INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Setup Pages
        id: config
        uses: actions/configure-pages@v5

      - name: Disable quotePath
        run: git config --global core.quotePath false

      - run: git --no-pager log -n 200

      - name: Build
        run: pnpm run build
        env:
          SITE_BASE_URL: ${{ steps.config.outputs.base_url }}

      - name: Setup IndexNow
        run: echo ${{ secrets.INDEXNOW_KEY }} > dist/IndexNow-${{ secrets.INDEXNOW_KEY }}.txt

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
