name: CD
on:
  workflow_call:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Build
        run: pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          single-commit: false
          folder: dist
          git-config-name: github-actions[bot]
          git-config-email: github-actions[bot]@users.noreply.github.com
