name: CD
on:
  workflow_run:
    workflows: CI
    branches: main
    types: completed
  workflow_dispatch:

jobs:
  Deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./setup-action

      - name: Generate static assets
        run: pnpm run build

      - name: Deploy to public repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: TheJiahao/TheJiahao.github.io
          publish_branch: main # default: gh-pages
          publish_dir: ./public
          commit_message: Deploy
