name: CI
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  Format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Format code
        run: yarn run format

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "style: Format code"
