name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    permissions:
      contents: write
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    uses: ./.github/workflows/ci.yml

  cd:
    name: CD
    needs: ci
    if: github.ref_name == 'main'
    secrets:
      INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
    concurrency:
      group: cd
      cancel-in-progress: true

    uses: ./.github/workflows/cd.yml
