name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    permissions:
      contents: write
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    uses: ./.github/workflows/ci.yml

  check:
    name: Check branch for CD
    needs: ci
    runs-on: ubuntu-latest
    if: ${{ github.ref_name }} == main
    steps:
      - run: echo "Continuing to CD"

  cd:
    name: CD
    needs: ci
    secrets:
      INDEXNOW_KEY: ${{ secrets.INDEXNOW_KEY }}
    concurrency:
      group: cd
      cancel-in-progress: true

    uses: ./.github/workflows/cd.yml
