name: End-to-end test
on:
  workflow_call:

jobs:
  e2e_test:
    name: End-to-end test
    runs-on: ubuntu-latest

    container: mcr.microsoft.com/playwright:v1.44.1-jammy
    environment: test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Run tests
        run: pnpm run test:e2e
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results
          path: test-results
          retention-days: 30
