name: End-to-end test
on:
  deployment_status:

jobs:
  e2e_test:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'

    name: End-to-end test
    runs-on: ubuntu-latest
    environment: test
    env:
      BASE_URL: ${{ github.event.deployment_status.environment_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-action

      - name: Run tests
        uses: docker://mcr.microsoft.com/playwright:v1.44.1-jammy
        with:
          args: npx playwright test
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-results
          path: test-results
          retention-days: 30
