name: Release
on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          commitMode: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                    "title": "## ⭐ 新功能",
                    "labels": ["feat"]
                },
                {
                    "title": "## 🚀 性能",
                    "labels": ["perf"]
                }
              ]
            }

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          body: ${{ steps.github_release.outputs.changelog }}
